development:
  adapter: async

test:
  adapter: async

production:
  # adapter: redis
  # url: redis://localhost:6379/1
    adapter: postgresql
    url: postgres://mttenuamuolouu:x5ztofv5t3OVEpZvyUdLM_Dboy@ec2-54-243-201-144.compute-1.amazonaws.com:5432/d552t79h5kuo86
